apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node:2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        command: ["sh", "-c", "node app.js"]
        volumeMounts:
        - name: secret-volume
          mountPath: "/var/secrets"
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 0700
          secretName: node-secret  
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080